
CREATE TABLE `USUARIO` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `nombre` VARCHAR(255) NOT NULL,
    `DNI` VARCHAR(255) NOT NULL,
    `dinero` INT
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `ADMINISTRADOR` (
    `contrasenya` VARCHAR(255) NOT NULL,
    `idAdministrador` INT,
    FOREIGN KEY (idAdministrador)
        REFERENCES USUARIO (id)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `EMPLEADO` (
    `numVentas` INT,
    `contrasenya` VARCHAR(255) NOT NULL,
    `idEmpleado` INT,
    FOREIGN KEY (idEmpleado)
        REFERENCES USUARIO (id)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `CLIENTE` (
    `comprasEnMes` INT,
    `VIP` BOOLEAN DEFAULT FALSE,
    `idCliente` INT,
    FOREIGN KEY (idCliente)
        REFERENCES USUARIO (id)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `DESCUENTO` (
    `codigo` VARCHAR(255) PRIMARY KEY,
    `descuento` INT NOT NULL
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `PRODUCTO` (
    `idProducto` INT AUTO_INCREMENT PRIMARY KEY,
    `cantidad` INT DEFAULT 0,
    `precio` INT NOT NULL
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `INDICO` (
    `catCalmante` INT NOT NULL,
    `catHambre` INT NOT NULL,
    `id` INT,
    FOREIGN KEY (id)
        REFERENCES PRODUCTO (idProducto)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;


CREATE TABLE `SATIMO` (
    `catEstimulante` INT NOT NULL,
    `catCreatividad` INT NOT NULL,
    `id` INT,
    FOREIGN KEY (id)
        REFERENCES PRODUCTO (idProducto)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;


CREATE TABLE `TIPO` (
    `raza` VARCHAR(255) NOT NULL,
    `cht` INT NOT NULL,
    `dbc` INT NOT NULL,
    `id` INT,
    FOREIGN KEY (id)
        REFERENCES PRODUCTO (idProducto)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;


CREATE TABLE `PROVEEDOR` (
    `IdProveedor` INT AUTO_INCREMENT PRIMARY KEY,
    `nombreEmpresa` VARCHAR(255) NOT NULL,
    `NIF` VARCHAR(255) NOT NULL
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;


CREATE TABLE `FACTURA` (
    `numeroDeFactura` INT AUTO_INCREMENT PRIMARY KEY,
    `idProveedor` INT NOT NULL,
    `idAdministrador` INT NOT NULL,
    `idProducto` INT NOT NULL,
    `importe` INT NOT NULL
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `RECIBO` (
    `numeroRecibo` INT AUTO_INCREMENT PRIMARY KEY,
    `importe` INT NOT NULL,
    `idProducto` INT NOT NULL,
    `idEmpleado` INT NOT NULL,
    `idCliente` INT NOT NULL,
    `descuento` INT NOT NULL
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;